steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/baksara-official/ml-api/ml-api-image',
        '.',
      ]

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast1-docker.pkg.dev/baksara-official/ml-api/ml-api-image',
      ]

  # Configure Docker for Artifact Registry using gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'configure-docker', 'asia-southeastq-docker.pkg.dev']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'python-api',
        '--image',
        'asia-southeast1-docker.pkg.dev/baksara-official/ml-api/ml-api-image',
        '--platform',
        'managed',
        '--region',
        'asia-southeast1',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
